default: ec2_yum_linux
ec2_yum_linux:
    cloud: ec2
    distro: redhat
    provisioner: yum
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_apt_linux:
    cloud: ec2
    distro: debian
    provisioner: apt
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_apt_chef_linux:
    cloud: ec2
    provisioner: apt_chef
    distro: debian
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_puppet_linux:
    cloud: ec2
    provisioner: apt_puppet
    distro: redhat
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs

